[package]
name = "koppeln"
version = "0.1.0"
authors = ["Hendrik Kunert <>"]
edition = "2018"

[dependencies]
bytes = "1.0.1"
nom = "5.1"
bitflags = "1.2"
toml = "0.5.6"
serde = { version = "1.0", features = ["derive"] }
config = "0.9"
log = "0.4"
env_logger = "0.7.1"
#tokio = { version = "0.2", features = ["full"] }
tokio = { version = "1.2", features = ["full"] }
warp = "0.3"
futures = "0.3"
tokio-util = { version = "0.6.3", features = ["net", "codec"] }

[dev-dependencies]
# testcontainers = "0.11"
testcontainers = { git = "https://github.com/kunerd/testcontainers-rs.git", branch = "add_udp_sctp_port_mappings" }
#testcontainers = { path = "../testcontainers-rs" }
spectral = "0.6.0"
pretty_env_logger = "0.4"
tempfile = "3.1"
trust-dns-client = "0.20"
reqwest = { version = "0.11", features = ["json"] }

[lib]
name = "koppeln"
path = "src/lib.rs"

[package.metadata.deb]
name = "koppeln"
section = "net"
#extended-description-file = "debian/description.txt"
#license-file = ["LICENSE", "0"]
#depends = "$auto, adduser, libssl1.1"
maintainer-scripts = "debian/"
#changelog = "debian/changelog" # this will be generated by the pkg workflow
#copyright = "Copyright (c) 2019, NLnet Labs. All rights reserved."
#assets = [
#    ["target/release/krill", "/usr/bin/krill", "755"],
#    ["target/release/krillc", "/usr/bin/krillc", "755"],
#    ["defaults/krill.conf", "/usr/share/doc/krill/krill.conf", "644"],
#    ["doc/krill.1", "/usr/share/man/man1/krill.1", "644"],
#    ["doc/krillc.1", "/usr/share/man/man1/krillc.1", "644"],
#    ["debian/krill.service.preset", "/lib/systemd/system-preset/50-krill.preset", "644"],
#]
systemd-units = { unit-name = "koppeln", enable = true }
