[package]
name = "dyndns"
version = "0.1.0"
authors = ["kunerd"]
edition = "2018"

[dependencies]
bytes = "0.5"
byteorder = "1.3"
nom = "5.1"
bitflags = "1.2"
toml = "0.5.6"
serde = { version = "1.0", features = ["derive"] }

[lib]
name = "dns"
path = "src/lib.rs"
