# syntax=docker/dockerfile:experimental
FROM rust:1.47-slim-buster as builder
WORKDIR /usr/src/dyndns
RUN cargo install cargo-deb
COPY . .
RUN --mount=type=cache,target=/usr/local/cargo/registry \
	--mount=type=cache,target=/usr/src/dyndns/target \
	cargo deb --output=./debian/ 

FROM debian:buster-slim
WORKDIR /tmp/dyndns
ENV DYNDNS_WEB_ADDRESS=0.0.0.0
ENV DYNDNS_DNS_ADDRESS=0.0.0.0
COPY --from=builder /usr/src/dyndns/debian/dyndns_0.1.0_amd64.deb ./
RUN dpkg -i dyndns_0.1.0_amd64.deb 
