[env]
DOCKER_BUILDKIT=1
DEB_FILE="koppeln_0.1.0_amd64.deb"

[config]
default_to_workspace = false

[tasks.package-deb]
command = "docker"
args = [
    "build",
    "-t", "koppeln-build",
    "-o", "./debian",
    "."
]

[tasks.lxc-setup]
script = [
    "lxc launch images:debian/11 koppeln",
    "sleep 5",
    "lxc launch images:debian/11 drill",
    "lxc exec drill -- apt-get install -y ldnsutils",
]
dependencies = [ "package-deb" ]

[tasks.lxc-cleanup]
script = [
    "lxc delete --force koppeln",
    "lxc delete --force drill",
]

[tasks.lxc-install]
script = [
    "lxc file push ./debian/${DEB_FILE} koppeln/tmp/${DEB_FILE}",
    "lxc exec koppeln -- dpkg -i /tmp/${DEB_FILE}",
    "lxc file push -p ./config/test.toml koppeln/etc/koppeln/config.toml",
    "lxc exec koppeln -- systemctl restart koppeln.service"
]

[tasks.lxc]
dependencies = [
    "lxc-cleanup",
    "lxc-setup",
    "lxc-install"
]

[tasks.e2e-tests]
#dependencies = [ "lxc" ]
command = "cargo"
args = [
    "test",
    "--test", "*",
    "--manifest-path", "e2e-tests/Cargo.toml",
    "--",
    "--test-threads=1",
    "--nocapture"
]
