[env]
DOCKER_BUILDKIT=1
DEB_FILE="koppeln_0.1.0_amd64.deb"

[config]
default_to_workspace = false

[tasks.package-deb]
command = "docker"
args = [
    "build",
    "-t", "koppeln-build",
    "-o", "./debian",
    "."
]

[tasks.cleanup-lxc-server-image]
ignore_errors = true
script = [
    "lxc delete --force koppeln-server-base"
]

[tasks.setup-lxc-server-image]
dependencies = [ "cleanup-lxc-server-image" ]
script = [
    "lxc launch images:debian/11 koppeln-server-base",
    "sleep 5",
    "lxc file push -p ./debian/${DEB_FILE} koppeln-server-base/tmp/${DEB_FILE}",
    "lxc file push -p ./debian/config.toml koppeln-server-base/etc/koppeln/config.toml",
    "lxc exec koppeln-server-base -- dpkg -i /tmp/${DEB_FILE}",
    "lxc snapshot --reuse koppeln-server-base snapshot",
    "lxc publish --compression=none koppeln-server-base/snapshot --alias koppeln-server",
]

[tasks.cleanup-lxc-client-image]
ignore_errors = true
script = [
    "lxc delete --force drill-client-base"
]

[tasks.setup-lxc-client-image]
dependencies = [ "cleanup-lxc-client-image" ]
script = [
    "lxc launch images:debian/11 drill-client-base",
    "lxc exec drill-client-base -- apt-get install -y ldnsutils",
    "lxc snapshot --reuse drill-client-base snapshot",
    "lxc publish --compression=none drill-client-base/snapshot --alias drill-client",
]

[tasks.setup-lxc]
dependencies = [
    "setup-lxc-server-image",
    "setup-lxc-client-image",
]

[tasks.e2e-tests]
dependencies = [ "setup-lxc" ]
command = "cargo"
args = [
    "test",
    "-p", "e2e_tests"
]
