[dns]
address = "127.0.0.1"
port = 5354

[dns.soa]
mname = "dyn.example.com"
rname = "postmaster.example.com"
serial = 1
refresh = 300
retry = 900
expire = 900
minimum = 300


[http]
address = "0.0.0.0"
port = 8088

[addresses]
"test" = { token = "super_secure" }
