---
name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust toolchain  make
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Cargo make
        uses: davidB/rust-cargo-make@v1

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Setup Docker layer cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build
        run: cargo make --profile=ci build

      - name: Unit tests
        run: cargo make --profile=ci test

      - name: Package DEB file
        run: cargo make --profile=ci package-deb

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Setup Linux Containers
        run: |
          sudo lxd init --minimal

          lxc --version

          sudo chmod o+g '/var/snap/lxd/common/lxd/unix.socket'

      - name: Run end-to-end tests
        run: cargo make --profile=ci e2e-tests
