---
name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust toolchain  make
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Cargo make
        uses: davidB/rust-cargo-make@v1

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Build
        run: cargo make build

      - name: Unit tests
        run: cargo make test

      - name: Package DEB file
        run: cargo make package-deb

      - name: Setup Linux Containers
        run: |
          sudo snap install lxd

          sudo lxd init --minimal

          lxc --version

          sudo chmod o+g '/var/snap/lxd/common/lxd/unix.socket'

      - name: Run end-to-end tests
        run: cargo make e2e-tests
